baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'OMSTest'

[module]

  #
  # Theme
  #
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
    disable = true

  #
  # Theme
  #
  [[module.imports]]
    path = "github.com/OMSTest/omstest-theme"
    disable = false