baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  
  #
  # Theme
  #
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
    disable = false

  #
  # Theme
  #
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = true