baseURL = 'https://omstest.github.io/'
languageCode = 'en-us'
title = 'OMSTest'

[module]

  #
  # Theme
  #
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
    disable = false