#!/bin/sh

if [ "" == "$1" ]; then
    echo "ERROR: You need to pass a number of the PR"
	exit 1
else
	pr=$1
fi

re='^[0-9]+$'
if ! [[ $pr =~ $re ]] ; then
   echo "ERROR: It's not a number" >&2; 
   exit 1
fi

git fetch origin pull/$pr/head

git pull origin pull/$pr/head